apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  # Het wachtwoord 'wordpress-db-password' in base64
  MYSQL_ROOT_PASSWORD: d29yZHByZXNzLWRiLXBhc3N3b3Jk
