apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-rolebinding
  namespace: wordpress
subjects:
  - kind: ServiceAccount
    name: wordpress-sa
    namespace: wordpress
roleRef:
  kind: Role
  name: wordpress-role
  apiGroup: rbac.authorization.k8s.io
